GET http://localhost:3000/categories/?take=2&skip=1

###
GET http://localhost:3000/categories/1

###
POST http://localhost:3000/categories
Content-Type: application/json

{
  "nom": "Books",
  "articles":[]
}

###
PATCH http://localhost:3000/categories
Content-Type: application/json

{
  "id":1,
  "nom": "SmartPhones",
  "articles":[]
}

###
DELETE http://localhost:3000/categories/9




